import type { D1Migration } from "cloudflare:test";

// `cloudflare:test` types its `env` as `Cloudflare.Env`, the interface
// generated by `wrangler types`, so a test-only binding has to be merged into
// that namespace rather than declared alongside it.
declare global {
  namespace Cloudflare {
    interface Env {
      /** Parsed migrations/ SQL, injected by vitest.config.ts. Test-only. */
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

export {};
