-- Adds config.model_type as a family-resolution source.
--
-- The Hub returns config.model_type in the same listing request we already
-- make — it just has to be asked for. Measured on 400 of the newest models it
-- resolves a further 11.5%, against a live "unknown" family rate of 53-63%,
-- which is the weakest number on the dashboard and answers one of the brief's
-- four questions.
--
-- COST: none. ADD COLUMN is metadata-only in SQLite; existing rows take NULL
-- lazily and no row is rewritten. Safe to apply at any time, with a run in
-- flight, on any plan.
--
-- This deliberately does NOT extend the resolution_source CHECK to include a
-- 'config_model_type' value. Doing so would mean rebuilding the table —
-- ~75,000 row writes, most of a day's free-plan budget, a maintenance window,
-- and a destructive DROP with no point-in-time restore on the Free plan — to
-- satisfy a constraint on a column that is written in five places and read in
-- none. resolveByModelType records NULL provenance instead; see the comment
-- there. If resolution_source ever gains a reader, extending the CHECK is a
-- table rebuild at that point, on purpose rather than by accident.

ALTER TABLE hf_models ADD COLUMN model_type TEXT;
