-- Records every pipeline run so one can be found and stopped.
--
-- Workflow instance ids are generated by Cloudflare at create() time and were
-- returned to the caller and then forgotten. The binding offers get(id) and
-- create(), but no way to list — so a run whose id was lost could only be
-- inspected or terminated through the Cloudflare dashboard by hand. A wedged
-- instance that nobody can stop is the one state that makes a schema
-- migration unsafe, because a table rebuild underneath a live run is exactly
-- what must not happen.
--
-- COST: a new empty table. No existing row is touched, so unlike 0003 this
-- costs effectively nothing against the daily write budget and is safe to
-- apply at any time.

CREATE TABLE hf_runs (
  instance_id  TEXT PRIMARY KEY,
  week_start   TEXT NOT NULL,
  params       TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(params)),
  started_at   TEXT NOT NULL,
  -- Last status observed by a caller of /api/admin/runs. Advisory only: the
  -- Workflow is the authority, this is a cache so the list is readable
  -- without fanning out to the binding for rows that already finished.
  last_status  TEXT,
  checked_at   TEXT
);

CREATE INDEX idx_runs_started ON hf_runs (started_at DESC);
